language: cpp

matrix:
  include:
    # Linux (GCC 8)
    - os: linux
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -qq g++-8
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
      script:
        - "./.travis/linux-gcc-7/build.sh"
        - "./.travis/linux-gcc-7/tests.sh"
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # OSX (Xcode 10.1)
    - os: osx
      osx_image: xcode10.1
      before_script:
        - "chmod +x ./.travis/macos-xcode-10.1/build.sh"
        - "chmod +x ./.travis/macos-xcode-10.1/tests.sh"
      script:
        - "./.travis/macos-xcode-10.1/build.sh"
        - "./.travis/macos-xcode-10.1/tests.sh"