language: cpp

matrix:
  include:
    # Linux (GCC 7)
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # Linux (Clang 5.0)
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
    # OSX (GCC 7)
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
    # OSX (Xcode 10.1)
    - os: osx
      osx_image: xcode10.1

before_script:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build

script:
  - cmake ..
  - make