language: cpp

matrix:
  include:
    # Linux (GCC 7)
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      install: "./.travis/linux-clang-5.0/dl_deps.sh"
      script:
        - "./.travis/linux-gcc-7/build.sh"
        - "./.travis/linux-gcc-7/tests.sh"
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # Linux (Clang 5.0)
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      install: "./.travis/linux-clang-5.0/dl_deps.sh"
      script:
        - "./.travis/linux-clang-5.0/build.sh"
        - "./.travis/linux-clang-5.0/tests.sh"
    # OSX (Xcode 10.1)
    - os: osx
      osx_image: xcode10.1
      before_script:
        - "chmod +x ./.travis/macos-xcode-10.1/build.sh"
        - "chmod +x ./.travis/macos-xcode-10.1/tests.sh"
      script:
        - "./.travis/macos-xcode-10.1/build.sh"
        - "./.travis/macos-xcode-10.1/tests.sh"